[package]
name = "hierarchy_labellisation"
version = "0.1.0"
license = "MIT"
repository = "https://github.com/IGNF/hierarchy_labellisation"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"

